version: "0.1"

networks:
  # Specify the network for bridging
  zkprover-circuit:
    driver: bridge

services:
  circuit:
    build: ./
    command: ./target/release/service
    restart: always
    networks:
        - zkprover-circuit
    volumes:
      - .data/rocksdb:/data/bundler-circuit/rocksdb/
      - .data/setup:/data/bundler-circuit/setup/